"""Add father_name, mother_name, permanent_address, correspondence_address, and Aadhaar-related columns to Student table

Revision ID: 837360d495db
Revises: 980601d71aba
Create Date: 2026-01-09 15:57:58.276405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '837360d495db'
down_revision = '980601d71aba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('father_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('mother_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('permanent_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('correspondence_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('student_aadhaar_photo', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('father_aadhaar_photo', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('mother_aadhaar_photo', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('mother_aadhaar_photo')
        batch_op.drop_column('father_aadhaar_photo')
        batch_op.drop_column('student_aadhaar_photo')
        batch_op.drop_column('correspondence_address')
        batch_op.drop_column('permanent_address')
        batch_op.drop_column('mother_name')
        batch_op.drop_column('father_name')

    # ### end Alembic commands ###
