"""Allow password_hash to be nullable

Revision ID: 980601d71aba
Revises: 052c10a2f772
Create Date: 2026-01-07 15:12:24.044592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '980601d71aba'
down_revision = '052c10a2f772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
