"""Add teacher.school_id and teacher.secret_key

Revision ID: eb0ba2d2ba30
Revises: 837360d495db
Create Date: 2026-01-27 07:38:56.584964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb0ba2d2ba30'
down_revision = '837360d495db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns using simple ALTER TABLE ADD COLUMN (supported by SQLite).
    op.add_column('teacher', sa.Column('school_id', sa.String(length=5), nullable=True))
    op.add_column('teacher', sa.Column('secret_key', sa.String(length=5), nullable=True))
    # Create a unique index for the secret_key to enforce uniqueness on SQLite.
    op.create_index('ix_teacher_secret_key', 'teacher', ['secret_key'], unique=True)

    # For SQLite, avoid rebuilding the whole table (which can fail if defaults
    # are not rendered as constants). Create the foreign key directly instead.
    op.create_foreign_key(
        'fk_tte_original_teacher_id_teacher',
        'teacher_timetable_entry', 'teacher',
        ['original_teacher_id'], ['id']
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the FK created above.
    op.drop_constraint('fk_tte_original_teacher_id_teacher', 'teacher_timetable_entry', type_='foreignkey')

    # Drop the unique index and the added columns.
    op.drop_index('ix_teacher_secret_key', table_name='teacher')
    op.drop_column('teacher', 'secret_key')
    op.drop_column('teacher', 'school_id')

    # ### end Alembic commands ###
